/-
Copyright (c) 2026 Junyan Xu. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Junyan Xu
-/
module

public import Mathlib.Algebra.MvPolynomial.PDeriv
public import Mathlib.AlgebraicGeometry.EllipticCurve.Projective.Point
public import Mathlib.Data.Fin.Tuple.Reflection
public import Mathlib.LinearAlgebra.CrossProduct
public import Mathlib.Tactic.Ring.NamePolyVars

/-!
# Reduction homomorphism associated to a Weierstrass curve
-/


namespace AlgebraicGeometry.ProjectiveSpace

variable (n m : Type*)

-- This is currently `WeierstrassCurve.Projective.PointClass`
abbrev PointClass (R : Type*) [Monoid R] :=
  MulAction.orbitRel.Quotient Rˣ (n → R)

variable {n m}

namespace PointClass

section Monoid

variable {R S : Type*} [Monoid R] [Monoid S] (f : R →* S)

abbrev map : PointClass n R → PointClass n S :=
  Quotient.map (f ∘ ·) fun _ _ ⟨u, h⟩ ↦
    ⟨u.map f, funext fun _ ↦ (map_mul f ..).symm.trans congr(f ($h _))⟩

abbrev map₂ : PointClass n R × PointClass m R → PointClass n S × PointClass m S :=
  Prod.map (map f) (map f)

-- map₃ ...

def ExistsUnit : PointClass n R → Prop :=
  Quotient.lift (∃ i, IsUnit <| · i) sorry

@[simp] lemma existsUnit_mk_iff {P : n → R} : ExistsUnit ⟦P⟧ ↔ ∃ i, IsUnit (P i) := .rfl

lemma ExistsUnit.map {P : PointClass n R} (hP : ExistsUnit P) : ExistsUnit (P.map f) := by
  rcases P; have ⟨i, hi⟩ := hP; exact ⟨i, hi.map f⟩

end Monoid

section Semiring

variable {R S : Type*} [Semiring R] [Semiring S] (f : R →+* S)

def SpanEqTop : PointClass n R → Prop :=
  Quotient.lift (fun x ↦ Ideal.span (.range x) = ⊤) sorry

@[simp]
lemma spanEqTop_mk_iff {P : n → R} : SpanEqTop ⟦P⟧ ↔ Ideal.span (.range P) = ⊤ := .rfl

lemma SpanEqTop.map {P : PointClass n R} (hP : SpanEqTop P) :
    SpanEqTop (P.map f.toMonoidHom) := by
  obtain ⟨P, rfl⟩ := Quotient.mk_surjective P
  rw [spanEqTop_mk_iff] at hP
  apply_fun Ideal.map f at hP
  rwa [Ideal.map_top, Ideal.map_span, ← Set.range_comp] at hP

lemma ExistsUnit.spanEqTop {P : PointClass n R} (hP : ExistsUnit P) : SpanEqTop P := by
  rcases P
  have ⟨i, hi⟩ := hP
  exact Ideal.eq_top_of_isUnit_mem _ (Ideal.subset_span ⟨i, rfl⟩) hi

end Semiring

theorem orbitRel_iff_of_span_eq_one {R} [CommSemiring R] {P Q : n → R}
    (hP : Ideal.span (Set.range P) = ⊤) (hQ : Ideal.span (Set.range Q) = ⊤) :
    MulAction.orbitRel Rˣ _ P Q ↔ ∀ i j, P i * Q j = P j * Q i where
  mp := by rintro ⟨u, rfl⟩; simp [Units.smul_def, mul_right_comm]
  mpr h := by
    have ⟨c, hc⟩ := Finsupp.mem_span_range_iff_exists_finsupp.mp ((Ideal.eq_top_iff_one _).mp hQ)
    let u := c.sum fun i a ↦ a • P i
    have h i : u * Q i = P i := by
      rw [← one_mul (P i), ← hc, c.sum_mul]
      dsimp; rw [c.sum_mul]
      simp_rw [mul_assoc, h, mul_comm]
    refine ⟨(Ideal.span_singleton_eq_top (x := u).mp <|
      top_unique <| .trans hP.ge <| Ideal.span_le.mpr ?_).unit, funext h⟩
    rintro _ ⟨i, rfl⟩
    rw [← h, mul_comm]
    exact Submodule.smul_mem _ _ (Ideal.subset_span rfl)

end AlgebraicGeometry.ProjectiveSpace.PointClass

namespace WeierstrassCurve.Projective

variable {R S : Type*} [CommRing R] [CommRing S] (f : R →+* S)
variable (W : WeierstrassCurve.Projective R)

/- Can replace the `Nonsingular` definition, which currently uses `≠ 0` conditions which are
good only in a field. Note that `SpanDerivEqTop` implies `SpanEqTop`, since the derivatives are
homogeneous of degree 2 in the coordinates x,y,z, so certainly in the ideal generated by x,y,z.
If this is defined to say one of the derivative is a unit, it doesn't imply one of x,y,z is a unit.
-/
def SpanDerivEqTop (P : Fin 3 → R) : Prop :=
  Ideal.span {W.polynomialX.eval P, W.polynomialY.eval P, W.polynomialZ.eval P} = ⊤

open AlgebraicGeometry ProjectiveSpace PointClass

-- TODO: replace `PointClass R` by `ProjectiveSpace.PointClass (Fin 3) R`

def EquationLift : PointClass R → Prop :=
  Quotient.lift W.Equation sorry
/- Note: if (x,y,z) satisfies Equation, then x³ ∈ span {y,z},
so span {x,y,z} = ⊤ ↔ span {y,z} = ⊤. -/

def SpanDerivEqTopLift : PointClass R → Prop :=
  Quotient.lift W.SpanDerivEqTop sorry

def point : Set (PointClass R) := {P | ExistsUnit P ∧ W.EquationLift P}

def nonsingularPoint : Set (PointClass R) := W.point ∩ {P | W.SpanDerivEqTopLift P}

local notation3 "x" => (0 : Fin 3)
local notation3 "y" => (1 : Fin 3)
local notation3 "z" => (2 : Fin 3)

def BX (P₁ P₂ : Fin 3 → R) : Fin 3 → R :=
  ![]


end WeierstrassCurve.Projective
